src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidatRepository::class)]
class Candidat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $CIN = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $CNE = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Nationnalite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(nullable: true)]
    private ?bool $fonctionnaire = null;

    #[ORM\ManyToOne(inversedBy: 'candidats')]
    private ?Post $post = null;

    #[ORM\ManyToOne(inversedBy: 'candidats')]
    private ?Session $session = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCIN(): ?string
    {
        return $this->CIN;
    }

    public function setCIN(string $CIN): self
    {
        $this->CIN = $CIN;

        return $this;
    }

    public function getCNE(): ?string
    {
        return $this->CNE;
    }

    public function setCNE(?string $CNE): self
    {
        $this->CNE = $CNE;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(?string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getNationnalite(): ?string
    {
        return $this->Nationnalite;
    }

    public function setNationnalite(?string $Nationnalite): self
    {
        $this->Nationnalite = $Nationnalite;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function isFonctionnaire(): ?bool
    {
        return $this->fonctionnaire;
    }

    public function setFonctionnaire(?bool $fonctionnaire): self
    {
        $this->fonctionnaire = $fonctionnaire;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): self
    {
        $this->session = $session;

        return $this;
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Form\DocumentType;
use App\Repository\DocumentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DocumentController extends AbstractController
{
    #[Route('/document', name: 'app_document_index', methods: ['GET'])]
    public function index(DocumentRepository $documentRepository): Response
    {
        return $this->render('document/table-datatable-document.html.twig', [
            'documents' => $documentRepository->findAll(),
        ]);
    }

    #[Route('/document_new', name: 'app_document_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DocumentRepository $documentRepository): Response
    {
        $document = new Document();
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $documentRepository->save($document, true);

            return $this->redirectToRoute('app_document_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('document/new.html.twig', [
            'document' => $document,
            'form' => $form,
        ]);
    }


    #[Route('/document_{id}_edit', name: 'app_document_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Document $document, DocumentRepository $documentRepository): Response
    {
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $documentRepository->save($document, true);

            return $this->redirectToRoute('app_document_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('document/edit.html.twig', [
            'document' => $document,
            'form' => $form,
        ]);
    }

    #[Route('/document_{id}_{_token}', name: 'app_document_delete', methods: ['GET', 'POST'])]
    public function delete(Request $request, Document $document, DocumentRepository $documentRepository , $_token): Response
    {
        if ($this->isCsrfTokenValid('delete'.$document->getId(), $_token)) {
            $documentRepository->remove($document, true);
        }

        return $this->redirectToRoute('app_document_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/document/attestation.html.twig

<!DOCTYPE html>
<html>
	<head>
		<title>Attestation</title>
		<meta charset="utf-8">

   		<link rel="stylesheet" href="https://efmpt.uae.ac.ma/e-fmpt/public/uplaods/css/document.css">
	</head>
	<body>
        <div class="label_fichier">
			Tanger le, {{ "now"|date("d/m/Y") }}
	    </div><br><br>
	       <h1>ATTESTATION DE TRAVAIL</h1>
        <div class="contenu_fichier"><br>
			<p> Le Doyen de la Faculté de Médecine de Tanger Atteste que:</p>
  
  			<table>
              <tr>
              	<th>
              		M.
              	</th>
              	<td style="text-transform:uppercase;">
              		:  {{personnel.nom}} {{personnel.prenom}}
              	</td>
              </tr>
	      			<tr>
                <th>
                  D.R.P.P 
                </th>
                <td>
                  : {{personnel.numPPR}} 
                </td>
              </tr>
              <tr>
              	<th>
              		Grade
              	</th>
              	<td>
              		: {{personnel.corpsId.designationFR}} 
              	</td>
              </tr>
           

{% if  ("ROLE_DIR_ADJ" in personnel.idUser.roles) or ("ROLE_PROF" in personnel.idUser.roles) or ("ROLE_CHEF_FIL" in personnel.idUser.roles) or ("ROLE_CHEF_DEP" in personnel.idUser.roles)  or ("ROLE_CHEF_SERV" in personnel.idUser.roles)  or ("ROLE_DIR" in personnel.idUser.roles)  %}

	      			<tr>
                <th>
                  Fonction  
                </th>
                <td>
                  : {{personnel.fonctionExercee.fonctionExercee}} 
                </td>
              </tr>
{% endif %}  
 



  			</table>
			
			
			<p><strong>Recruté(e) dans </strong><br><br><br>
        <span>L'Administration à compter du {{ personnel.dateRecrutement|date('Y-m-d') }} </span><span style="float: right; padding-right: 80px;"></span>
			 <br>
       <span>Exerce à l'FMPT depuis le {{ personnel.dateAffectationENSAT|date('Y-m-d') }}</span><span style="float: right; padding-right: 80px;"></span>
			 <br></p><br>

			<p> La présente attestation est délivrée à la demande de l'interessé(e) pour servir et valoir ce que de droit.</p>
		</div>
	</body>
</html>

templates/document/bonsortie.html.twig
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
<title></title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
 <br/>
<style type="text/css">
    body{
      margin-left:20px;
      margin-right:20px;
    }
    .label_fichier{
      font-size: 20px;
      text-align: right;
      padding-top: 15%;
    }
    h1{
      font-size: 20px;
      font-weight: bold;
      text-align: center;
      padding-top: 10px;
      margin-bottom:10px;
    }
    p{
      text-align: justify;
      font-size:20px;
    }
    
    .right {
      text-align: right;
      margin-right: 1em;
    }

    .center {
      text-align: center;
    }
    .left {
      text-align: left;
      margin-left: 1em;
    }
    table {

      font-family : "Times New Roman", Arial, Verdana, Sans-serif;
      margin-right: 5%;
      width:90%;

      
    }

    table, th, td {
      font-size:18px;
      padding-right: 5px;
      padding-top:10px;
    }
<!--
	p {margin: 0; padding: 0;}	.ft10{font-size:13px;font-family:Times;color:#404040;}
	.ft11{font-size:14px;font-family:Times;color:#000000;}
	.ft12{font-size:31px;font-family:Times;color:#000000;}
	.ft13{font-size:13px;font-family:Times;color:#000000;}
	.ft14{font-size:10px;font-family:Helvetica;color:#000000;}
	.ft15{font-size:11px;font-family:Times;color:#000000;}
	.ft16{font-size:14px;font-family:Times;color:#000000;}
	.ft17{font-size:13px;font-family:Times;color:#000000;}
	table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}

td,th{
	padding: 10px;
}
-->
</style>
</head>
<body vlink="blue" link="blue">
<div id="page1-div" style="position:relative;width:892px;height:1262px;">
<!--img width="892" height="1262" src="target001.png" alt="background image"/-->


<p style="position:absolute;top:269px;left:66px;white-space:nowrap" class="ft11">N° Décharge :</p>
<p style="position:absolute;top:188px;left:389px;white-space:nowrap" class="ft12"><b>Décharge</b></p>
<p style="position:absolute;top:269px;left:219px;white-space:nowrap" class="ft13"><b>{{decharge.numdecharge}}</b></p>
<p style="position:absolute;top:314px;left:66px;white-space:nowrap" class="ft14">Je&#160;soussigné(e)&#160;Mr/Mme&#160;{{decharge.personnel.prenom}}&#160;{{decharge.personnel.nom}}</p>
<p style="position:absolute;top:218px;left:66px;white-space:nowrap" class="ft14">EXERCICE:</p>
<p style="position:absolute;top:160px;left:646px;white-space:nowrap" class="ft15">Service Logistique et Magasinage</p>
<p style="position:absolute;top:267px;left:396px;white-space:nowrap" class="ft11">Date :</p>
<p style="position:absolute;top:269px;left:442px;white-space:nowrap" class="ft13"><b>{{decharge.datedecharge|date("d/m/Y")}}</b></p>
<p style="position:absolute;top:214px;left:157px;white-space:nowrap" class="ft13"><b>{{decharge.exercice}}</b></p>
<p style="position:absolute;top:43px;left:122px;white-space:nowrap" class="ft16"><b>Royaume du Maroc&#160;</b></p>
<p style="position:absolute;top:43px;left:722px;white-space:nowrap" class="ft16"><b>المملكة المغربية&#160;</b></p>
<p style="position:absolute;top:62px;left:82px;white-space:nowrap" class="ft16"><b>Université Abdelmalek Essaâdi&#160;</b></p>
<p style="position:absolute;top:62px;left:708px;white-space:nowrap" class="ft16"><b>جامعة عبد المالك السعدي&#160;</b></p>
<p style="position:absolute;top:81px;left:60px;white-space:nowrap" class="ft16"><b>Faculté de Médecine et de Pharmacie&#160;</b></p>
<p style="position:absolute;top:81px;left:725px;white-space:nowrap" class="ft16"><b>كلية الطب والصيدلة&#160;</b></p>
<p style="position:absolute;top:99px;left:167px;white-space:nowrap" class="ft16"><b>Tanger&#160;</b></p>
<p style="position:absolute;top:99px;left:740px;white-space:nowrap" class="ft16"><b>طنجة&#160;</b></p>
<p style="position:absolute;top:17px;left:339px;white-space:nowrap" class="ft16"><img src="https://efmpt.uae.ac.ma/e-fmpt/public/fmpt.png" alt="" width="250"></p>
<p style="position:absolute;top:335px;left:66px;white-space:nowrap" class="ft14">Service / Local: {{decharge.personnel.serviceaffectationid.nomservice}} /  {{decharge.local}} &#160;</p>
<p style="position:absolute;top:355px;left:66px;white-space:nowrap" class="ft14">Atteste&#160;avoir&#160;reçu&#160;le&#160;matériel&#160;designe&#160;ci-dessous:</p>

<table style="position:absolute;top:399px;left:59px;width:100%;text-align:center !important;">
<th>Désignation article</th>
<th>Reference article</th>
<th>Quantite</th>

{% for inv in decharge.affectations %}

<tr>
<td>{{inv.article.reference}}</td>
<td>{{inv.article.designation}}</td>
<td>{{inv.qte}}</td>
</tr>

{% endfor %}

</table>











<p style="position:absolute;top:963px;left:55px;white-space:nowrap" class="ft17">CERTIFIE LA SORTIE&#160;</p>
<p style="position:absolute;top:981px;left:77px;white-space:nowrap" class="ft17">DU MATERIEL</p>
<p style="position:absolute;top:964px;left:693px;white-space:nowrap" class="ft17">CERTIFIE LA RECEPTION&#160;</p>
<p style="position:absolute;top:981px;left:728px;white-space:nowrap" class="ft17">DU MATERIEL</p>
<p style="position:absolute;top:1028px;left:48px;white-space:nowrap" class="ft17">SERVICE MATERIEL ET&#160;</p>
<p style="position:absolute;top:1046px;left:86px;white-space:nowrap" class="ft17">FINANCIER</p>
<p style="position:absolute;top:1037px;left:383px;white-space:nowrap" class="ft17">LE MAGASINIER</p>
<p style="position:absolute;top:1037px;left:721px;white-space:nowrap" class="ft17">LE DESTINATAIRE</p>
<p style="position:absolute;top:1194px;left:131px;white-space:nowrap" class="ft17">Faculté de Médecine et de Pharmacie de Tanger B.P.365 Gzanaya, km 15, Route de Rabat - Tanger</p>
<p style="position:absolute;top:1217px;left:319px;white-space:nowrap" class="ft17">Tel. : 0539.39.37.44 Fax : 0539.39.73.43</p>

</div>
</body>
</html>

templates/document/decharge.html.twig
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
<title></title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
 <br/>
<style type="text/css">
    body{
      margin-left:20px;
      margin-right:20px;
    }
    .label_fichier{
      font-size: 20px;
      text-align: right;
      padding-top: 15%;
    }
    h1{
      font-size: 20px;
      font-weight: bold;
      text-align: center;
      padding-top: 10px;
      margin-bottom:10px;
    }
    p{
      text-align: justify;
      font-size:20px;
    }
    
    .right {
      text-align: right;
      margin-right: 1em;
    }

    .center {
      text-align: center;
    }
    .left {
      text-align: left;
      margin-left: 1em;
    }
    table {

      font-family : "Times New Roman", Arial, Verdana, Sans-serif;
      margin-right: 5%;
      width:90%;

      
    }

    table, th, td {
      font-size:18px;
      padding-right: 5px;
      padding-top:10px;
    }
<!--
	p {margin: 0; padding: 0;}	.ft10{font-size:13px;font-family:Times;color:#404040;}
	.ft11{font-size:14px;font-family:Times;color:#000000;}
	.ft12{font-size:31px;font-family:Times;color:#000000;}
	.ft13{font-size:13px;font-family:Times;color:#000000;}
	.ft14{font-size:10px;font-family:Helvetica;color:#000000;}
	.ft15{font-size:11px;font-family:Times;color:#000000;}
	.ft16{font-size:14px;font-family:Times;color:#000000;}
	.ft17{font-size:13px;font-family:Times;color:#000000;}
	table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}

td,th{
	padding: 10px;
}
-->
</style>
</head>
<body vlink="blue" link="blue">
<div id="page1-div" style="position:relative;width:892px;height:1262px;">
<!--img width="892" height="1262" src="target001.png" alt="background image"/-->


<p style="position:absolute;top:269px;left:66px;white-space:nowrap" class="ft11">N° Décharge :</p>
<p style="position:absolute;top:188px;left:389px;white-space:nowrap" class="ft12"><b>Décharge</b></p>
<p style="position:absolute;top:269px;left:219px;white-space:nowrap" class="ft13"><b>{{decharge.numdecharge}}</b></p>
<p style="position:absolute;top:314px;left:66px;white-space:nowrap" class="ft14">Je&#160;soussigné(e)&#160;Mr/Mme&#160;{{decharge.personnel.prenom}}&#160;{{decharge.personnel.nom}}</p>
<p style="position:absolute;top:218px;left:66px;white-space:nowrap" class="ft14">EXERCICE:</p>
<p style="position:absolute;top:160px;left:646px;white-space:nowrap" class="ft15">Service Logistique et Magasinage</p>
<p style="position:absolute;top:267px;left:396px;white-space:nowrap" class="ft11">Date :</p>
<p style="position:absolute;top:269px;left:442px;white-space:nowrap" class="ft13"><b>{{decharge.datedecharge|date("d/m/Y")}}</b></p>
<p style="position:absolute;top:214px;left:157px;white-space:nowrap" class="ft13"><b>{{decharge.exercice}}</b></p>
<p style="position:absolute;top:43px;left:122px;white-space:nowrap" class="ft16"><b>Royaume du Maroc&#160;</b></p>
<p style="position:absolute;top:43px;left:722px;white-space:nowrap" class="ft16"><b>المملكة المغربية&#160;</b></p>
<p style="position:absolute;top:62px;left:82px;white-space:nowrap" class="ft16"><b>Université Abdelmalek Essaâdi&#160;</b></p>
<p style="position:absolute;top:62px;left:708px;white-space:nowrap" class="ft16"><b>جامعة عبد المالك السعدي&#160;</b></p>
<p style="position:absolute;top:81px;left:60px;white-space:nowrap" class="ft16"><b>Faculté de Médecine et de Pharmacie&#160;</b></p>
<p style="position:absolute;top:81px;left:725px;white-space:nowrap" class="ft16"><b>كلية الطب والصيدلة&#160;</b></p>
<p style="position:absolute;top:99px;left:167px;white-space:nowrap" class="ft16"><b>Tanger&#160;</b></p>
<p style="position:absolute;top:99px;left:740px;white-space:nowrap" class="ft16"><b>طنجة&#160;</b></p>
<p style="position:absolute;top:17px;left:339px;white-space:nowrap" class="ft16"><img src="https://efmpt.uae.ac.ma/e-fmpt/public/fmpt.png" alt="" width="250"></p>
<p style="position:absolute;top:335px;left:66px;white-space:nowrap" class="ft14">Service / Local: {{decharge.personnel.serviceaffectationid.nomservice}} /  {{decharge.local}} &#160;</p>
<p style="position:absolute;top:355px;left:66px;white-space:nowrap" class="ft14">Atteste&#160;avoir&#160;reçu&#160;le&#160;matériel&#160;designe&#160;ci-dessous:</p>

<table style="position:absolute;top:399px;left:59px;width:100%;text-align:center !important;">
<th>N° Inventaire</th>
<th>Désignation article</th>
<th>quantité</th>
<th>Observations</th>

{% for affectation in decharge.affectations %}

<tr>
<td>{{affectation.inventaire.numinventaire}}</td>
<td>{{affectation.inventaire.article.designation}}</td>
<td>1</td>
<td>{{affectation.inventaire.remarque}}</td>
</tr>

{% endfor %}

</table>











<p style="position:absolute;top:963px;left:55px;white-space:nowrap" class="ft17">CERTIFIE LA SORTIE&#160;</p>
<p style="position:absolute;top:981px;left:77px;white-space:nowrap" class="ft17">DU MATERIEL</p>
<p style="position:absolute;top:964px;left:693px;white-space:nowrap" class="ft17">CERTIFIE LA RECEPTION&#160;</p>
<p style="position:absolute;top:981px;left:728px;white-space:nowrap" class="ft17">DU MATERIEL</p>
<p style="position:absolute;top:1028px;left:48px;white-space:nowrap" class="ft17">SERVICE MATERIEL ET&#160;</p>
<p style="position:absolute;top:1046px;left:86px;white-space:nowrap" class="ft17">FINANCIER</p>
<p style="position:absolute;top:1037px;left:383px;white-space:nowrap" class="ft17">LE MAGASINIER</p>
<p style="position:absolute;top:1037px;left:721px;white-space:nowrap" class="ft17">LE DESTINATAIRE</p>
<p style="position:absolute;top:1194px;left:131px;white-space:nowrap" class="ft17">Faculté de Médecine et de Pharmacie de Tanger B.P.365 Gzanaya, km 15, Route de Rabat - Tanger</p>
<p style="position:absolute;top:1217px;left:319px;white-space:nowrap" class="ft17">Tel. : 0539.39.37.44 Fax : 0539.39.73.43</p>

</div>
</body>
</html>

templates/document/dechargebloc.html.twig
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
<title></title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
 <br/>
<style type="text/css">
    body{
      margin-left:20px;
      margin-right:20px;
    }
    .label_fichier{
      font-size: 20px;
      text-align: right;
      padding-top: 15%;
    }
    h1{
      font-size: 20px;
      font-weight: bold;
      text-align: center;
      padding-top: 10px;
      margin-bottom:10px;
    }
    p{
      text-align: justify;
      font-size:20px;
    }
    
    .right {
      text-align: right;
      margin-right: 1em;
    }

    .center {
      text-align: center;
    }
    .left {
      text-align: left;
      margin-left: 1em;
    }
    table {

      font-family : "Times New Roman", Arial, Verdana, Sans-serif;
      margin-right: 5%;
      width:90%;

      
    }

    table, th, td {
      font-size:18px;
      padding-right: 5px;
      padding-top:10px;
    }
<!--
	p {margin: 0; padding: 0;}	.ft10{font-size:13px;font-family:Times;color:#404040;}
	.ft11{font-size:14px;font-family:Times;color:#000000;}
	.ft12{font-size:31px;font-family:Times;color:#000000;}
	.ft13{font-size:13px;font-family:Times;color:#000000;}
	.ft14{font-size:10px;font-family:Helvetica;color:#000000;}
	.ft15{font-size:11px;font-family:Times;color:#000000;}
	.ft16{font-size:14px;font-family:Times;color:#000000;}
	.ft17{font-size:13px;font-family:Times;color:#000000;}
	table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}

td,th{
	padding: 10px;
}
-->
</style>
</head>
<body vlink="blue" link="blue">
<div id="page1-div" style="position:relative;width:892px;height:1262px;">
<!--img width="892" height="1262" src="target001.png" alt="background image"/-->


<p style="position:absolute;top:269px;left:66px;white-space:nowrap" class="ft11">N° Décharge :</p>
<p style="position:absolute;top:188px;left:389px;white-space:nowrap" class="ft12"><b>Décharge</b></p>
<p style="position:absolute;top:269px;left:219px;white-space:nowrap" class="ft13"><b>{{decharge.numdecharge}}</b></p>
<p style="position:absolute;top:314px;left:66px;white-space:nowrap" class="ft14">Je&#160;soussigné(e)&#160;Mr/Mme&#160;{{decharge.personnel.prenom}}&#160;{{decharge.personnel.nom}}</p>
<p style="position:absolute;top:218px;left:66px;white-space:nowrap" class="ft14">EXERCICE:</p>
<p style="position:absolute;top:160px;left:646px;white-space:nowrap" class="ft15">Service Logistique et Magasinage</p>
<p style="position:absolute;top:267px;left:396px;white-space:nowrap" class="ft11">Date :</p>
<p style="position:absolute;top:269px;left:442px;white-space:nowrap" class="ft13"><b>{{decharge.datedecharge|date("d/m/Y")}}</b></p>
<p style="position:absolute;top:214px;left:157px;white-space:nowrap" class="ft13"><b>{{decharge.exercice}}</b></p>
<p style="position:absolute;top:43px;left:122px;white-space:nowrap" class="ft16"><b>Royaume du Maroc&#160;</b></p>
<p style="position:absolute;top:43px;left:722px;white-space:nowrap" class="ft16"><b>المملكة المغربية&#160;</b></p>
<p style="position:absolute;top:62px;left:82px;white-space:nowrap" class="ft16"><b>Université Abdelmalek Essaâdi&#160;</b></p>
<p style="position:absolute;top:62px;left:708px;white-space:nowrap" class="ft16"><b>جامعة عبد المالك السعدي&#160;</b></p>
<p style="position:absolute;top:81px;left:60px;white-space:nowrap" class="ft16"><b>Faculté de Médecine et de Pharmacie&#160;</b></p>
<p style="position:absolute;top:81px;left:725px;white-space:nowrap" class="ft16"><b>كلية الطب والصيدلة&#160;</b></p>
<p style="position:absolute;top:99px;left:167px;white-space:nowrap" class="ft16"><b>Tanger&#160;</b></p>
<p style="position:absolute;top:99px;left:740px;white-space:nowrap" class="ft16"><b>طنجة&#160;</b></p>
<p style="position:absolute;top:17px;left:339px;white-space:nowrap" class="ft16"><img src="https://efmpt.uae.ac.ma/e-fmpt/public/fmpt.png" alt="" width="250"></p>
<p style="position:absolute;top:335px;left:66px;white-space:nowrap" class="ft14">Service / Local: {{decharge.personnel.serviceaffectationid.nomservice}} /  {{decharge.local}} &#160;</p>
<p style="position:absolute;top:355px;left:66px;white-space:nowrap" class="ft14">Atteste&#160;avoir&#160;reçu&#160;le&#160;matériel&#160;designe&#160;ci-dessous:</p>

<table style="position:absolute;top:399px;left:59px;width:100%;text-align:center !important;">
<th>Désignation article</th>
<th>N° Inventaire</th>
<th>Quantite</th>
<th>Observations</th>

{% for bloc in blocs %}

<tr>
<td>{{bloc.designation}}</td>
<td style="font-size: 8.5px;">
{% for affectation in decharge.affectations %}
{% if affectation.inventaire.article.designation == bloc.designation %}
{{affectation.inventaire.numinventaire}}<br/>
{% endif %}
{% endfor %}
</td>
<td>{{bloc.qte}}</td>
<td>
{% for affectation in decharge.affectations %}
{% if affectation.inventaire.article.designation == bloc.designation %}
{% if affectation.inventaire.remarque %}{{affectation.inventaire.numinventaire}} : {{affectation.inventaire.remarque}}{% endif %}<br/>
{% endif %}
{% endfor %}
</td>
</tr>

{% endfor %}

</table>











<p style="position:absolute;top:963px;left:55px;white-space:nowrap" class="ft17">CERTIFIE LA SORTIE&#160;</p>
<p style="position:absolute;top:981px;left:77px;white-space:nowrap" class="ft17">DU MATERIEL</p>
<p style="position:absolute;top:964px;left:693px;white-space:nowrap" class="ft17">CERTIFIE LA RECEPTION&#160;</p>
<p style="position:absolute;top:981px;left:728px;white-space:nowrap" class="ft17">DU MATERIEL</p>
<p style="position:absolute;top:1028px;left:48px;white-space:nowrap" class="ft17">SERVICE MATERIEL ET&#160;</p>
<p style="position:absolute;top:1046px;left:86px;white-space:nowrap" class="ft17">FINANCIER</p>
<p style="position:absolute;top:1037px;left:383px;white-space:nowrap" class="ft17">LE MAGASINIER</p>
<p style="position:absolute;top:1037px;left:721px;white-space:nowrap" class="ft17">LE DESTINATAIRE</p>
<p style="position:absolute;top:1194px;left:131px;white-space:nowrap" class="ft17">Faculté de Médecine et de Pharmacie de Tanger B.P.365 Gzanaya, km 15, Route de Rabat - Tanger</p>
<p style="position:absolute;top:1217px;left:319px;white-space:nowrap" class="ft17">Tel. : 0539.39.37.44 Fax : 0539.39.73.43</p>

</div>
</body>
</html>